### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Escapingbug** [Escapingbug/ancypwn#3]
# Todos

* [x] URGENT! clear resource used by stopped container when `end`
* [x] write tutorial for macos users so they can get `ancypwn` running with full terminal support
* [x] update readme so it fits the newest version
* [x] upload 18.04 image
* [x] update script so environment setups can be well dealt with.
* [x] update script to loose version limitation (one can always use preferred version if you have image)
* [x]  explain a little bit of internals in readme, so it can be customized
* [ ] solve xquatz DISPLAY problem. current DISPLAY environ setup under macos is still not usable with xquatz installation

# Things not decided how to solve yet

* [ ] xserver security issue (`xhost +` currently allows any clients to connect)
